config/routes.rb
Shuttle::Application.routes.draw do
  resources :accesses

  resources :challenges

  resources :faqs

  resources :trips

  resources :devices

  resources :transport_canada_registrations

  resources :otto_view_raw_trips

  get "pages/about"
  get "pages/about_summerhill_impact"
  get "pages/baseline"
  get "pages/challenge"
  get "pages/contact"
  get "pages/drive_better"
  get "pages/drive_less"
  get "pages/faq"
  get "pages/how_shuttle_works"
  get "pages/how_shuttle_works_detail"
  get "pages/install"
  get "pages/payout"
  get "pages/privacy"
  get "pages/rewards"
  get "pages/rewards_detail"
  get "pages/supporters"
  get "pages/survey"
  get "pages/training"
  get "pages/typography"           # testing only
  get "pages/value_of_shuttle"
  get "pages/why_shuttle"
  get "pages/why_shuttle_detail"


  resources :posts

  resources :snippets

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/transport_canada_registration.rb
class TransportCanadaRegistration < ActiveRecord::Base
  attr_protected :whynot
  
  # create the user associated objects
  def find_or_create_user

    # create the user  
    email = self.accesscode.to_s+"@shuttlechallenge.ca"
    user = User.where(email: email).first

    if user.nil? # no duplicate users please
      password = self.accesscode
      name = "#{self.firstname} #{self.lastname}"
      user = User.new(name: name, email: email, password: password)

      
      #create the access object for this user
      user.access = Access.new(code: password)



      #device
      user.device= Device.new(device: self.logger_id)
      user.save!

    end
    user
  end

end

app/controllers/transport_canada_registrations_controller.rb
class TransportCanadaRegistrationsController < ApplicationController
  include ActiveModel::MassAssignmentSecurity
  # GET /transport_canada_registrations
  # GET /transport_canada_registrations.json
  def index
    @transport_canada_registrations = TransportCanadaRegistration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transport_canada_registrations }
    end
  end

  # GET /transport_canada_registrations/1
  # GET /transport_canada_registrations/1.json
  def show
    @transport_canada_registration = TransportCanadaRegistration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transport_canada_registration }
    end
  end

  # GET /transport_canada_registrations/new
  # GET /transport_canada_registrations/new.json
  def new
    @transport_canada_registration = TransportCanadaRegistration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transport_canada_registration }
    end
  end

  # GET /transport_canada_registrations/1/edit
  def edit
    @transport_canada_registration = TransportCanadaRegistration.find(params[:id])
  end
  def cull_params
    role = :default
    sanitize_for_mass_assignment(params[:transport_canada_registration], role)
  end
  # POST /transport_canada_registrations
  # POST /transport_canada_registrations.json
  def create
    
    @transport_canada_registration = TransportCanadaRegistration.new(cull_params)

    respond_to do |format|
      if @transport_canada_registration.save
        format.html { redirect_to @transport_canada_registration, notice: 'Transport canada registration was successfully created.' }
        format.json { render json: @transport_canada_registration, status: :created, location: @transport_canada_registration }
      else
        format.html { render action: "new" }
        format.json { render json: @transport_canada_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transport_canada_registrations/1
  # PUT /transport_canada_registrations/1.json
  def update
    @transport_canada_registration = TransportCanadaRegistration.find(params[:id])

    respond_to do |format|
      if @transport_canada_registration.update_attributes(params[:transport_canada_registration])
        format.html { redirect_to @transport_canada_registration, notice: 'Transport canada registration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transport_canada_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transport_canada_registrations/1
  # DELETE /transport_canada_registrations/1.json
  def destroy
    @transport_canada_registration = TransportCanadaRegistration.find(params[:id])
    @transport_canada_registration.destroy

    respond_to do |format|
      format.html { redirect_to transport_canada_registrations_url }
      format.json { head :no_content }
    end
  end

end

app/views/transport_canada_registrations/_form.html.haml
= form_for @transport_canada_registration do |f|
  -if @transport_canada_registration.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transport_canada_registration.errors.count, "error")} prohibited this transport_canada_registration from being saved:"
      %ul
        - @transport_canada_registration.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :e_mailaddress
    = f.text_field :e_mailaddress 
  .field
    = f.label :accesscode
    = f.text_field :accesscode
  .field
    = f.label :logger_id
    = f.number_field :logger_id
  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :lastname
    = f.text_field :lastname  
  .field
    = f.label :start_date
    = f.datetime_select :start_date    
  .field
    = f.label :end_date
    = f.datetime_select :end_date 
    
  .field
    = f.label :logger_partvin
    = f.text_field :logger_partvin
  .field
    = f.label :callresult
    = f.text_field :callresult
  .field
    = f.label :l_type
    = f.text_field :l_type
  .field
    = f.label :batch
    = f.text_field :batch
  .field
    = f.label :province
    = f.text_field :province
  .field
    = f.label :preflanguage
    = f.text_field :preflanguage
  

  .field
    = f.label :phonenumber
    = f.text_field :phonenumber

  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :postalcode
    = f.text_field :postalcode
  .field
    = f.label :vehicle
    = f.text_field :vehicle
  .field
    = f.label :vin
    = f.text_field :vin
  .field
    = f.label :province
    = f.text_field :province
  .field
    = f.label :havevehicle
    = f.text_field :havevehicle
  .field
    = f.label :since_day
    = f.text_field :since_day
  .field
    = f.label :since_month
    = f.text_field :since_month
  .field
    = f.label :since_year
    = f.text_field :since_year
  .field
    = f.label :name_2
    = f.text_field :name_2
  .field
    = f.label :gender_2
    = f.text_field :gender_2
  .field
    = f.label :yob_2
    = f.text_field :yob_2
  .field
    = f.label :name_3
    = f.text_field :name_3
  .field
    = f.label :gender_3
    = f.text_field :gender_3
  .field
    = f.label :yob_3
    = f.text_field :yob_3
  .field
    = f.label :name_4
    = f.text_field :name_4
  .field
    = f.label :gender_4
    = f.text_field :gender_4
  .field
    = f.label :yob_4
    = f.text_field :yob_4
  .field
    = f.label :name_5
    = f.text_field :name_5
  .field
    = f.label :gender_5
    = f.text_field :gender_5
  .field
    = f.label :yob_5
    = f.text_field :yob_5
  .field
    = f.label :name_6
    = f.text_field :name_6
  .field
    = f.label :gender_6
    = f.text_field :gender_6
  .field
    = f.label :yob_6
    = f.text_field :yob_6
  .field
    = f.label :age_range_2
    = f.text_field :age_range_2
  .field
    = f.label :age_range_3
    = f.text_field :age_range_3
  .field
    = f.label :age_range_4
    = f.text_field :age_range_4
  .field
    = f.label :age_range_5
    = f.text_field :age_range_5
  .field
    = f.label :age_range_6
    = f.text_field :age_range_6
  .field
    = f.label :yearofbirthanswered
    = f.text_field :yearofbirthanswered
  .field
    = f.label :age
    = f.text_field :age
  .field
    = f.label :agerange
    = f.text_field :agerange
  .field
    = f.label :gender
    = f.text_field :gender
  .field
    = f.label :typeoffuel
    = f.text_field :typeoffuel
  .field
    = f.label :transmission
    = f.text_field :transmission
  .field
    = f.label :completedonline
    = f.text_field :completedonline
  .field
    = f.label :finalstatus
    = f.text_field :finalstatus

  .field
    = f.label :assigndate
    = f.datetime_select :assigndate
  .field
    = f.label :returndate
    = f.datetime_select :returndate
  .actions
    = f.submit 'Save'

app/views/transport_canada_registrations/edit.html.haml
%h1 Editing transport_canada_registration

= render 'form'

= link_to 'Show', @transport_canada_registration
\|
= link_to 'Back', transport_canada_registrations_path

app/views/transport_canada_registrations/index.html.haml
%h1 Listing transport_canada_registrations

%table
  %tr
    %th Accesscode
    %th Logger partvin
    %th Callresult
    %th L type
    %th Batch
    %th Province
    %th Preflanguage
    %th Start date
    %th End date
    %th Firstname
    %th Lastname
    %th Phonenumber
    %th E mailaddress
    %th Number
    %th Street
    %th City
    %th Postalcode
    %th Vehicle
    %th Vin
    %th Province
    %th Havevehicle
    %th Whynot
    %th Since day
    %th Since month
    %th Since year
    %th Name 2
    %th Gender 2
    %th Yob 2
    %th Name 3
    %th Gender 3
    %th Yob 3
    %th Name 4
    %th Gender 4
    %th Yob 4
    %th Name 5
    %th Gender 5
    %th Yob 5
    %th Name 6
    %th Gender 6
    %th Yob 6
    %th Age range 2
    %th Age range 3
    %th Age range 4
    %th Age range 5
    %th Age range 6
    %th Yearofbirthanswered
    %th Age
    %th Agerange
    %th Gender
    %th Typeoffuel
    %th Transmission
    %th Completedonline
    %th Finalstatus
    %th Logger
    %th Assigndate
    %th Returndate
    %th
    %th
    %th

  - @transport_canada_registrations.each do |transport_canada_registration|
    %tr
      %td= transport_canada_registration.accesscode
      %td= transport_canada_registration.logger_partvin
      %td= transport_canada_registration.callresult
      %td= transport_canada_registration.l_type
      %td= transport_canada_registration.batch
      %td= transport_canada_registration.province
      %td= transport_canada_registration.preflanguage
      %td= transport_canada_registration.start_date
      %td= transport_canada_registration.end_date
      %td= transport_canada_registration.firstname
      %td= transport_canada_registration.lastname
      %td= transport_canada_registration.phonenumber
      %td= transport_canada_registration.e_mailaddress
      %td= transport_canada_registration.number
      %td= transport_canada_registration.street
      %td= transport_canada_registration.city
      %td= transport_canada_registration.postalcode
      %td= transport_canada_registration.vehicle
      %td= transport_canada_registration.vin
      %td= transport_canada_registration.province
      %td= transport_canada_registration.havevehicle
      %td= transport_canada_registration.whynot
      %td= transport_canada_registration.since_day
      %td= transport_canada_registration.since_month
      %td= transport_canada_registration.since_year
      %td= transport_canada_registration.name_2
      %td= transport_canada_registration.gender_2
      %td= transport_canada_registration.yob_2
      %td= transport_canada_registration.name_3
      %td= transport_canada_registration.gender_3
      %td= transport_canada_registration.yob_3
      %td= transport_canada_registration.name_4
      %td= transport_canada_registration.gender_4
      %td= transport_canada_registration.yob_4
      %td= transport_canada_registration.name_5
      %td= transport_canada_registration.gender_5
      %td= transport_canada_registration.yob_5
      %td= transport_canada_registration.name_6
      %td= transport_canada_registration.gender_6
      %td= transport_canada_registration.yob_6
      %td= transport_canada_registration.age_range_2
      %td= transport_canada_registration.age_range_3
      %td= transport_canada_registration.age_range_4
      %td= transport_canada_registration.age_range_5
      %td= transport_canada_registration.age_range_6
      %td= transport_canada_registration.yearofbirthanswered
      %td= transport_canada_registration.age
      %td= transport_canada_registration.agerange
      %td= transport_canada_registration.gender
      %td= transport_canada_registration.typeoffuel
      %td= transport_canada_registration.transmission
      %td= transport_canada_registration.completedonline
      %td= transport_canada_registration.finalstatus
      %td= transport_canada_registration.logger_id
      %td= transport_canada_registration.assigndate
      %td= transport_canada_registration.returndate
      %td= link_to 'Show', transport_canada_registration
      %td= link_to 'Edit', edit_transport_canada_registration_path(transport_canada_registration)
      %td= link_to 'Destroy', transport_canada_registration, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Transport canada registration', new_transport_canada_registration_path

app/views/transport_canada_registrations/new.html.haml
%h1 New transport_canada_registration

= render 'form'

= link_to 'Back', transport_canada_registrations_path

app/views/transport_canada_registrations/show.html.haml
%p#notice= notice

%p
  %b Accesscode:
  = @transport_canada_registration.accesscode
%p
  %b Logger partvin:
  = @transport_canada_registration.logger_partvin
%p
  %b Callresult:
  = @transport_canada_registration.callresult
%p
  %b L type:
  = @transport_canada_registration.l_type
%p
  %b Batch:
  = @transport_canada_registration.batch
%p
  %b Province:
  = @transport_canada_registration.province
%p
  %b Preflanguage:
  = @transport_canada_registration.preflanguage
%p
  %b Start date:
  = @transport_canada_registration.start_date
%p
  %b End date:
  = @transport_canada_registration.end_date
%p
  %b Firstname:
  = @transport_canada_registration.firstname
%p
  %b Lastname:
  = @transport_canada_registration.lastname
%p
  %b Phonenumber:
  = @transport_canada_registration.phonenumber
%p
  %b E mailaddress:
  = @transport_canada_registration.e_mailaddress
%p
  %b Number:
  = @transport_canada_registration.number
%p
  %b Street:
  = @transport_canada_registration.street
%p
  %b City:
  = @transport_canada_registration.city
%p
  %b Postalcode:
  = @transport_canada_registration.postalcode
%p
  %b Vehicle:
  = @transport_canada_registration.vehicle
%p
  %b Vin:
  = @transport_canada_registration.vin
%p
  %b Province:
  = @transport_canada_registration.province
%p
  %b Havevehicle:
  = @transport_canada_registration.havevehicle
%p
  %b Whynot:
  = @transport_canada_registration.whynot
%p
  %b Since day:
  = @transport_canada_registration.since_day
%p
  %b Since month:
  = @transport_canada_registration.since_month
%p
  %b Since year:
  = @transport_canada_registration.since_year
%p
  %b Name 2:
  = @transport_canada_registration.name_2
%p
  %b Gender 2:
  = @transport_canada_registration.gender_2
%p
  %b Yob 2:
  = @transport_canada_registration.yob_2
%p
  %b Name 3:
  = @transport_canada_registration.name_3
%p
  %b Gender 3:
  = @transport_canada_registration.gender_3
%p
  %b Yob 3:
  = @transport_canada_registration.yob_3
%p
  %b Name 4:
  = @transport_canada_registration.name_4
%p
  %b Gender 4:
  = @transport_canada_registration.gender_4
%p
  %b Yob 4:
  = @transport_canada_registration.yob_4
%p
  %b Name 5:
  = @transport_canada_registration.name_5
%p
  %b Gender 5:
  = @transport_canada_registration.gender_5
%p
  %b Yob 5:
  = @transport_canada_registration.yob_5
%p
  %b Name 6:
  = @transport_canada_registration.name_6
%p
  %b Gender 6:
  = @transport_canada_registration.gender_6
%p
  %b Yob 6:
  = @transport_canada_registration.yob_6
%p
  %b Age range 2:
  = @transport_canada_registration.age_range_2
%p
  %b Age range 3:
  = @transport_canada_registration.age_range_3
%p
  %b Age range 4:
  = @transport_canada_registration.age_range_4
%p
  %b Age range 5:
  = @transport_canada_registration.age_range_5
%p
  %b Age range 6:
  = @transport_canada_registration.age_range_6
%p
  %b Yearofbirthanswered:
  = @transport_canada_registration.yearofbirthanswered
%p
  %b Age:
  = @transport_canada_registration.age
%p
  %b Agerange:
  = @transport_canada_registration.agerange
%p
  %b Gender:
  = @transport_canada_registration.gender
%p
  %b Typeoffuel:
  = @transport_canada_registration.typeoffuel
%p
  %b Transmission:
  = @transport_canada_registration.transmission
%p
  %b Completedonline:
  = @transport_canada_registration.completedonline
%p
  %b Finalstatus:
  = @transport_canada_registration.finalstatus
%p
  %b Logger:
  = @transport_canada_registration.logger_id
%p
  %b Assigndate:
  = @transport_canada_registration.assigndate
%p
  %b Returndate:
  = @transport_canada_registration.returndate

= link_to 'Edit', edit_transport_canada_registration_path(@transport_canada_registration)
\|
= link_to 'Back', transport_canada_registrations_path