config/routes.rb
Shuttle::Application.routes.draw do
  resources :accesses

  resources :challenges

  resources :faqs

  resources :trips

  resources :devices

  resources :transport_canada_registrations

  resources :otto_view_raw_trips

  get "pages/about"
  get "pages/about_summerhill_impact"
  get "pages/baseline"
  get "pages/challenge"
  get "pages/contact"
  get "pages/drive_better"
  get "pages/drive_less"
  get "pages/faq"
  get "pages/how_shuttle_works"
  get "pages/how_shuttle_works_detail"
  get "pages/install"
  get "pages/payout"
  get "pages/privacy"
  get "pages/rewards"
  get "pages/rewards_detail"
  get "pages/supporters"
  get "pages/survey"
  get "pages/training"
  get "pages/typography"           # testing only
  get "pages/value_of_shuttle"
  get "pages/why_shuttle"
  get "pages/why_shuttle_detail"


  resources :posts

  resources :snippets

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  # GET /accesses
  # GET /accesses.json
  def index
    @accesses = Access.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accesses }
    end
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
    @access = Access.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @access }
    end
  end

  # GET /accesses/new
  # GET /accesses/new.json
  def new
    @access = Access.new
    
    unless current_user.nil?
      redirect_to root_url, notice: "User already signed in."
    else
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @access }
      end
    end
  end

  # GET /accesses/1/edit
  def edit
    unless current_user.nil?
      if current_user.has_role? :admin
        @access = Access.find(params[:id])
      else
      
        @access = current_user.access
      end
    else
      redirect_to new_access_url, notice: "Please sign in with your access code"
    end

  end

  # actually a lookup.
  def create
    input = Access.new(params[:access])
    puts "params" + params.to_yaml
    puts "input.code" + input.code
    @access = Access.find_by_code(input.code)
    puts @access.to_yaml
    if !@access.nil?
      
    end
    respond_to do |format|
      unless @access.nil?
        # valid code
        if @access.user.nil?
          puts "no user for this access object. Shouldn't happen"
          format.html { redirect_to root_url, notice: "No user for this access object."}
        else
          #sign in success
          user = @access.user
          puts user.to_yaml
          sign_in(user)
          puts "user signed in"
          puts @access.to_yaml
          if ((@access.username.nil? || @access.username.size == 0) || (@access.location.nil? || @access.location.size == 0) ) #need ancillary
            @access.username = @access.user.name.split[0]
            reg = TransportCanadaRegistration.find_by_accesscode(@access.code)
            @access.location = reg.city if (!reg.nil? && reg.city.size > 0)
            @access.save
            format.html { redirect_to edit_access_url(@access), notice: "Please add a username and location"}
          else
            format.html { redirect_to root_url, notice: "Signed in via access code #{@access.code} for #{@access.user.name}." }
            format.json { render json: @access, status: :created, location: @access }
          end
          
        end

      else
        #invalid code
        @access = Access.new
        flash[:error] = 'Invalid access code.'
        format.html { redirect_to new_access_url }

      end
    end
  end

  # PUT /accesses/1
  # PUT /accesses/1.json
  def update
    @access = Access.find(params[:id])

    respond_to do |format|
      if @access.update_attributes(params[:access])
        format.html { redirect_to root_url, notice: 'Access was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    @access = Access.find(params[:id])
    @access.destroy

    respond_to do |format|
      format.html { redirect_to accesses_url }
      format.json { head :no_content }
    end
  end
end

app/views/accesses/_form.html.haml
= form_for @access do |f|
  -if @access.errors.any?
    #error_explanation
      %h2= "#{pluralize(@access.errors.count, "error")} prohibited this access from being saved:"
      %ul
        - @access.errors.full_messages.each do |msg|
          %li= msg

  -if !current_user.nil? && (current_user.has_role? :admin)
    .field
      = f.label :user_id
      = f.number_field :user_id
  -if action_name == 'new'
    .field
      = f.label 'Access Code'
      = f.text_field :code
  -if action_name == 'edit'  
    .field
      = f.label :username
      = f.text_field :username
    .field
      = f.label :location
      = f.text_field :location
  .actions
    = f.submit ((action_name == 'new')? "Sign In" : 'Save'),  class: "button btn btn-danger btn-large btn-block"

app/views/accesses/edit.html.haml
%h1 Edit your username and location


= render 'form'

app/views/accesses/index.html.haml
%h1 Listing accesses

%table
  %tr
    %th User
    %th Code
    %th Username
    %th Location
    %th
    %th
    %th

  - @accesses.each do |access|
    %tr
      %td= access.user_id
      %td= access.code
      %td= access.username
      %td= access.location
      %td= link_to 'Show', access
      %td= link_to 'Edit', edit_access_path(access)
      %td= link_to 'Destroy', access, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Access', new_access_path

app/views/accesses/new.html.haml
/Access New - sign in (can't crate a new one)
%h1 Sign in with your Transfer Canada Access Code

= render 'form'

app/views/accesses/show.html.haml
%p#notice= notice

%p
  %b User:
  = @access.user_id
%p
  %b Code:
  = @access.code
%p
  %b Username:
  = @access.username
%p
  %b Location:
  = @access.location

= link_to 'Edit', edit_access_path(@access)
\|
= link_to 'Back', accesses_path